require('dotenv').config();

const TEMPORARY_PDF_PATH = "/tmp/generated_pdfs";
const TEMPORARY_UPLOAD_PATH = '/tmp/uploaded_docx';
const TEMPORARY_LIBREOFFICE_PROFILES_PATH = '/tmp/libreoffice_profiles';
const ENV_CLEANUP_AUTOMATION_DRY_MODE = process.env.CLEANUP_AUTOMATION_DRY_MODE === 'ON';
const ENV_CLEANUP_AUTOMATION_INTERVAL_MS = Number(process.env.CLEANUP_AUTOMATION_INTERVAL_MS);
const ENV_FILE_MAX_AGE_IN_SECONDS = Number(process.env.FILE_MAX_AGE_IN_SECONDS);
const ENV_PORT = Number(process.env.PORT);

module.exports = {
  TEMPORARY_PDF_PATH,
  TEMPORARY_UPLOAD_PATH,
  TEMPORARY_LIBREOFFICE_PROFILES_PATH,
  ENV_CLEANUP_AUTOMATION_DRY_MODE,
  ENV_CLEANUP_AUTOMATION_INTERVAL_MS,
  ENV_FILE_MAX_AGE_IN_SECONDS,
  ENV_PORT
};
